cache:
  paths:
  - vendor/

variables:
  DATABASE_URL: "mysql://db_user@db_password/db_name"

stages:
  - build
  - deploy

build:
  stage: build
  script:
  - echo "Building the app"
  - composer install --no-interaction --no-progress
  - sed -i -e "s|\$DATABASE_URL|$DATABASE_URL1|g" ".env"
  - ls -al
  - cat .env
  - bin/console doctrine:database:create --if-not-exists --verbose
  - bin/console doctrine:migrations:migrate --verbose

deploy_dev:
  stage: deploy
  script:
  - echo "Deploy to dev server"
  - ls -al
  - cat .env
  environment:
    name: dev
    url: http://it09.dev.mb.org/
  only:
  - develop
  - master
